from __future__ import annotations

import json
import logging
import random
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from openai import AsyncOpenAI

from app.schemas import MockLiveKitRequest, ParticipantInput
from app.settings import settings

logger = logging.getLogger(__name__)


SYSTEM_PROMPT = """
Eres un generador de transcripciones de llamadas.
Responde SOLO un objeto JSON valido con esta forma:
{
  "segments": [
    {"speaker": "user", "text": "..."},
    {"speaker": "agent", "text": "..."}
  ]
}
Reglas:
- Usa espanol natural y profesional.
- Genera exactamente el numero de turnos solicitado.
- Alterna user/agent.
- Cada turno debe tener una frase breve y creible.
- No incluyas markdown ni texto extra fuera del JSON.
""".strip()


def _resolve_identity(participant: ParticipantInput, fallback: str) -> str:
    if participant.identity:
        return participant.identity
    return fallback


async def generate_livekit_transcription_payload(
    request: MockLiveKitRequest,
) -> dict[str, Any]:
    raw_segments = await _generate_segments(request)
    return _build_livekit_payload(request, raw_segments)


async def _generate_segments(request: MockLiveKitRequest) -> list[dict[str, str]]:
    if settings.openai_api_key:
        try:
            return await _segments_from_openai(request)
        except Exception as exc:  # pragma: no cover - fallback behavior is intentional
            logger.warning("OpenAI generation failed, using fallback: %s", exc)
    return _fallback_segments(request)


async def _segments_from_openai(request: MockLiveKitRequest) -> list[dict[str, str]]:
    client = AsyncOpenAI(api_key=settings.openai_api_key)
    user_prompt = {
        "language": request.language,
        "turns": request.turns,
        "call_context": request.call_context,
        "user_name": request.user.name,
        "agent_name": request.agent.name,
        "objectives": request.objectives,
    }

    completion = await client.chat.completions.create(
        model=settings.openai_model,
        response_format={"type": "json_object"},
        temperature=0.7,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(user_prompt, ensure_ascii=True)},
        ],
    )

    content = completion.choices[0].message.content or "{}"
    parsed = json.loads(content)
    candidate_segments = parsed.get("segments")
    if not isinstance(candidate_segments, list):
        raise ValueError("OpenAI response does not contain a valid segments list.")

    cleaned_segments: list[dict[str, str]] = []
    for index, segment in enumerate(candidate_segments[: request.turns]):
        if not isinstance(segment, dict):
            continue
        speaker = str(segment.get("speaker", "")).lower().strip()
        if speaker not in {"user", "agent"}:
            speaker = "user" if index % 2 == 0 else "agent"
        text = str(segment.get("text", "")).strip()
        if not text:
            continue
        cleaned_segments.append({"speaker": speaker, "text": text})

    if len(cleaned_segments) < 4:
        raise ValueError("Insufficient transcription segments generated by OpenAI.")

    return cleaned_segments


def _fallback_segments(request: MockLiveKitRequest) -> list[dict[str, str]]:
    objective = request.objectives[0] if request.objectives else "resolver una consulta"
    user_openers = [
        f"Hola, soy {request.user.name} y necesito ayuda con este tema.",
        f"Gracias por atenderme, quisiera avanzar con {objective.lower()}.",
        "Tengo algunas dudas y me gustaria confirmar los pasos.",
    ]
    agent_openers = [
        f"Hola {request.user.name}, soy {request.agent.name}. Te acompano con gusto.",
        "Perfecto, revisemos juntos los detalles para darte una solucion clara.",
        "Entendido, voy a guiarte paso a paso para dejar esto resuelto.",
    ]
    user_followups = [
        "Mi prioridad es que quede claro el siguiente paso.",
        "Quiero asegurarme de que no falte ningun requisito.",
        "Me serviria confirmar tiempos y responsables.",
    ]
    agent_followups = [
        "Excelente, te comparto un plan concreto para continuar.",
        "Queda registrado y te explico el flujo de aqui en adelante.",
        "Buena pregunta; te doy una respuesta breve y accionable.",
    ]

    segments: list[dict[str, str]] = []
    for index in range(request.turns):
        speaker = "user" if index % 2 == 0 else "agent"
        if index == 0:
            text = random.choice(user_openers)
        elif index == 1:
            text = random.choice(agent_openers)
        elif speaker == "user":
            text = random.choice(user_followups)
        else:
            text = random.choice(agent_followups)
        segments.append({"speaker": speaker, "text": text})

    return segments


def _build_livekit_payload(
    request: MockLiveKitRequest,
    raw_segments: list[dict[str, str]],
) -> dict[str, Any]:
    now_iso = datetime.now(timezone.utc).isoformat()
    current_time = 0.0
    lk_segments: list[dict[str, Any]] = []

    for index, segment in enumerate(raw_segments):
        gap = random.uniform(0.2, 0.8)
        duration = random.uniform(1.0, 2.8)
        start_time = current_time + gap
        end_time = start_time + duration
        current_time = end_time

        is_user = segment["speaker"] == "user"
        participant = request.user if is_user else request.agent
        participant_identity = _resolve_identity(
            participant, "caller_user" if is_user else "agent_virtual"
        )

        lk_segments.append(
            {
                "id": f"SG_{uuid4().hex[:12]}",
                "speaker": segment["speaker"],
                "participantIdentity": participant_identity,
                "participantName": participant.name,
                "text": segment["text"],
                "language": request.language,
                "startTime": round(start_time, 3),
                "endTime": round(end_time, 3),
                "final": True,
            }
        )

    return {
        "event": "room.transcription.final",
        "source": "livekit-mock",
        "callId": request.call_id,
        "room": {"name": request.room_name},
        "createdAt": now_iso,
        "metadata": request.metadata,
        "transcription": {
            "language": request.language,
            "segments": lk_segments,
            "text": " ".join(segment["text"] for segment in lk_segments),
        },
    }
